project_id = "yvbwadjufdhnqfrzfjxq"

[functions.google-maps-proxy]
verify_jwt = false

[functions.process-recurring]
verify_jwt = false

[functions.contractor-link-info]
verify_jwt = false

[functions.contractor-submit]
verify_jwt = false