ALTER TABLE public.home_items
  ADD COLUMN IF NOT EXISTS system_key TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS is_registry_skeleton BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;